language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
branches:
  only:
    - master
install:
  - "cpanm -n --installdeps ."
notifications:
  email: sugama@jamadam.com
